[package]
name = "headway"
version = "1.0.1"
description = "Standalone roadmap planning tool"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
strip = true
