// Generic seed fixture (2026-08-14): structure mirrors the source workbook Roadmap tab,
// text content is genericized sample data. Do not hand-edit item data.
(function(root){
  var SEED = {
   "meta": {
    "title": "Product Roadmap",
    "timelineStart": "2026-07-27",
    "weeksPerSprint": 2,
    "numSprints": 24,
    "sprintDates": [
     "2026-07-27",
     "2026-08-10",
     "2026-08-24",
     "2026-09-07",
     "2026-09-21",
     "2026-10-05",
     "2026-10-19",
     "2026-11-02",
     "2026-11-16",
     "2026-11-30",
     "2026-12-14",
     "2026-12-28",
     "2027-01-11",
     "2027-01-25",
     "2027-02-08",
     "2027-02-22",
     "2027-03-08",
     "2027-03-22",
     "2027-04-05",
     "2027-04-19",
     "2027-05-03",
     "2027-05-17",
     "2027-05-31",
     "2027-06-14"
    ],
    "blackoutWeeks": [
     "2026-11-16",
     "2026-11-23",
     "2026-12-28",
     "2027-01-04"
    ]
   },
   "phases": [
    {
     "id": "bp1",
     "name": "Build Phase 1",
     "bucket": false,
     "collapsed": true,
     "description": ""
    },
    {
     "id": "mvp-diagnosis",
     "name": "MVP: Diagnosis",
     "bucket": false,
     "collapsed": false,
     "description": "End-to-end journey from diagnosis through execution for the pilot initiative type plus 2-3 others (AKA use cases). Key items out of scope: intake, measurement phase, creative agents, channel-specific expert agents."
    },
    {
     "id": "mvp-strategy",
     "name": "MVP: Strategy",
     "bucket": false,
     "collapsed": false,
     "description": ""
    },
    {
     "id": "mvp-execution",
     "name": "MVP: Execution",
     "bucket": false,
     "collapsed": false,
     "description": ""
    },
    {
     "id": "next",
     "name": "Next",
     "bucket": true,
     "collapsed": false,
     "description": "Annual Planning support, Measurement, Competitive and Execution data, long-term tech alignment"
    },
    {
     "id": "future",
     "name": "Future",
     "bucket": true,
     "collapsed": false,
     "description": ""
    }
   ],
   "items": [
    {
     "row": 5,
     "num": 1,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "OS Prototype Integration",
     "enables": "Data Office and consulting partner collaboration",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build",
     "size": "M",
     "risk": "M",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 6,
     "num": 3,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Initiative List",
     "enables": "Marketers should be able to view pilot programs (initiatives) in the tool. Data will be manually created and loaded in.",
     "outOfScope": "Project list, Loading in",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "S",
     "risk": "S",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 7,
     "num": 4,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Spine",
     "enables": "Marketers to navigate the blueprint process from beginning to end",
     "outOfScope": "Measurement phase activities",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "XS",
     "risk": "S",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 8,
     "num": 5,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Skills and Capabilities",
     "enables": "Agents to be able to share and utilize specific skills (context) to accomplish tasks",
     "outOfScope": "Skill development outside of BP1 skills",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "S",
     "risk": "S",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 9,
     "num": 6,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Data Sources (BP1)",
     "enables": "Agents to be given or restricted access to specific data sources and datasets",
     "outOfScope": "Data source development - other features cover this. Restrictions different from \"read-only to all sets within the integration\".",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "XS",
     "risk": "M",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 10,
     "num": 7,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Agent Transparency",
     "enables": "Marketers to be see what agents did, and how they arrived at their answer",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "S",
     "risk": "S",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 11,
     "num": 9,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Artifact Review",
     "enables": "Marketers to review artifacts in OS and collaborate with agents",
     "outOfScope": "Anyone can approve anything in this version, future versions will have specific role-based or individual approval chain",
     "notes": "",
     "deps": [
      1
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build",
     "size": "S",
     "risk": "S",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 12,
     "num": 10,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Authentication (SSO / Identity Provider)",
     "enables": "Data Office pattern compliance",
     "outOfScope": "Role-based features and access control in OS",
     "notes": "",
     "deps": [
      1
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build",
     "size": "S",
     "risk": "S",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 13,
     "num": 11,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Agents",
     "feature": "Context Gathering Agent Team (BP1)",
     "enables": "Marketers to draft Context Gathering insights in OS",
     "outOfScope": "Research into non-pilot use cases",
     "notes": "Includes at least the following agents: Context Gathering Team Lead, Market Segmentation Analyst Agent, Market Opportunity & Sizing Analysis Agent, Customer & Demand Segment Agent, Strategy Insight Analysis Agent",
     "deps": [
      1,
      2
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Stakeholder convo",
     "size": "L",
     "risk": "M",
     "startDay": 0,
     "durDays": 20,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 14,
     "num": 12,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Insights Data Integration via Knowledge API",
     "enables": "Opportunity Map Dashboard data (along with other insights platform data sources) to be utilized by agents in the OS",
     "outOfScope": "Direct access to any data sources - will go through Knowledge API",
     "notes": "",
     "deps": [
      1
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Knowledge API Access, Knowledge API feature readiness",
     "size": "M",
     "risk": "M",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 15,
     "num": 13,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Research Data Integration via Document API",
     "enables": "Research Repository data to be utilized by agents in the OS",
     "outOfScope": "Guardrails around usage and age restrictions",
     "notes": "",
     "deps": [
      1
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Research Repository Data in the Document API, Research Repository Access (lower priority)",
     "size": "M",
     "risk": "M",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 16,
     "num": 14,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Terms & Taxonomy Integration (BP1)",
     "enables": "Agents in OS to understand and correctly utilize the enterprise marketing terminology",
     "outOfScope": "Keeping terms up-to-date, this will be a one-time load",
     "notes": "",
     "deps": [
      1
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Terms and Taxonomy Data Ready",
     "size": "S",
     "risk": "M",
     "startDay": 0,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 17,
     "num": 8,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "OS",
     "feature": "Source Citation and Display",
     "enables": "Marketers to see clear source citations within the tool for artifacts, and be able to quickly access the original documents associated with the source data",
     "outOfScope": "Page-level highlighting or navigation to a specific page on a document",
     "notes": "",
     "deps": [
      12,
      13
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Research Repository Data in the Document API, Knowledge API Access",
     "size": "S",
     "risk": "S",
     "startDay": 10,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 18,
     "num": 15,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Agents",
     "feature": "Artifact Agent",
     "enables": "Member of the global agent team. Generated artifacts to match the requirements.",
     "outOfScope": "Evals, guardrails, quality gates that evaluate and increase quality and success rate",
     "notes": "",
     "deps": [
      1,
      2,
      9
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Brief Builder in pre-UAT code freeze",
     "size": "M",
     "risk": null,
     "startDay": 10,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 19,
     "num": 16,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Brief Builder Integration (BP1)",
     "enables": "Marketers to create a marketing brief in OS",
     "outOfScope": "Briefs other than Marketing Brief. Marketers to upload their own documents. AI building the brief (stub not ready by start).",
     "notes": "Will be considered as a member of the Strategy Agent team",
     "deps": [
      1
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Platform team to implement stub",
     "size": "M",
     "risk": null,
     "startDay": 10,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 20,
     "num": 17,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Agents",
     "feature": "Strategy Agent Team (BP1)",
     "enables": "Marketers to complete selected parts of the Strategy phase in the OS",
     "outOfScope": "Research into non-pilot use cases",
     "notes": "Includes the following agents: Brief Builder, Strategy Team Lead",
     "deps": [
      1,
      2
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Permit to Build, Sample Documents, Expert Convo",
     "size": "M",
     "risk": null,
     "startDay": 10,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 21,
     "num": 18,
     "phaseId": "bp1",
     "workstream": "",
     "epic": "Testing",
     "feature": "Demo & Validation Testing",
     "enables": "Marketers to be able to try a sample pilot initiative with AI first-hand (in a controlled, time-limited, non-production environment) through the in-scope portions of brief development. Goal is to get buy-in to continue the process and understand what was highest value for marketers.",
     "outOfScope": "UAT or deep quality review, evals",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "List of marketers / stakeholders in validation sessions",
     "size": "M",
     "risk": null,
     "startDay": 20,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "B8D0ED",
     "bucketMark": null
    },
    {
     "row": 23,
     "num": 0,
     "phaseId": "mvp-diagnosis",
     "workstream": "All",
     "epic": "OS",
     "feature": "Team Onboarding",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Staffing, Access",
     "size": "S",
     "risk": "M",
     "startDay": 20,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 24,
     "num": 68,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Agent Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": 20,
     "durDays": 40,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 25,
     "num": 20,
     "phaseId": "mvp-diagnosis",
     "workstream": "Data",
     "epic": "Data",
     "feature": "MVP Phase Data Catalogue Discovery and Development",
     "enables": "With data access in hand, additional discovery and integration approach recommendation for data sources. Gain additional fidelity on maturity where access permits. Specifically focusing on Strategy and Execution, plus additional Diagnosis items that were not built in BP1. Test across all use cases defined.",
     "outOfScope": "Restricted / sensitive data integration (or any data integration that would require significantly higher approval / compliance bar).\n\nAgency data and public ingestion integrations are not in scope. They could be uploaded manually and we could still identify that they are in these places and NOT in the enterprise.\n\nthe enterprise data owners responsible for data quality in all cases.",
     "notes": "Include any uncertain external agent discovery (Consumer, the martech vendor, etc.). Also investigating Measurement, but this is not dependent for MVP completion.",
     "deps": [
      57
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Full access to the data warehouse, Research Repository, and other defined data sources\nOpporunity Map Dashboard data available in",
     "size": "XL",
     "risk": "L",
     "startDay": 30,
     "durDays": 40,
     "leadDays": 10,
     "barColor": "F79646",
     "bucketMark": null
    },
    {
     "row": 26,
     "num": 21,
     "phaseId": "mvp-diagnosis",
     "workstream": "Data",
     "epic": "Data",
     "feature": "Data Governance Research",
     "enables": "Data from insightful, as well as ALL data sources, to have a defined governance process and data stewardship process",
     "outOfScope": "Implementation of the governance changes, these are handled in other features",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Research Repository team alignment",
     "size": "M",
     "risk": "XL",
     "startDay": 30,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "F79646",
     "bucketMark": null
    },
    {
     "row": 27,
     "num": 36,
     "phaseId": "mvp-diagnosis",
     "workstream": "Data",
     "epic": "OS",
     "feature": "Data Stewardship",
     "enables": "Data stewards to manage data access and policies, see output quality feedback from marketers when AI uses a data source, and enhance/evaluate quality through evaluations",
     "outOfScope": "",
     "notes": "",
     "deps": [
      22
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Data owners for MVP defined, process alignment",
     "size": "M",
     "risk": "L",
     "startDay": 60,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "F79646",
     "bucketMark": null
    },
    {
     "row": 28,
     "num": 30,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Evals / Quality Checks (Eval Tooling)",
     "enables": "Marketers to be able to influence quality of agent outcomes by defining quality checks and gates. Data Office to have first major integration with Eval Tooling. Align with Data Office & knowledge stewardship process alongside the knowledge domains.",
     "outOfScope": "Implementing the real evals / quality checks, this happens in the agent",
     "notes": "",
     "deps": [
      57
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Lead marketers on tap for eval discovery, Eval Tooling set up by the enterprise, Eval Tooling access",
     "size": "XL",
     "risk": "L",
     "startDay": 30,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 29,
     "num": 23,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "Integrations",
     "feature": "Audience Optimizer Agent Integration",
     "enables": "Agents to access and discuss possible strategies and insights with persona agents, resulting in more aligned outcomes",
     "outOfScope": "Changes to the audience optimizer agent",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Audience Optimizer in Agent Platform",
     "size": "S",
     "risk": "M",
     "startDay": 50,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 30,
     "num": 26,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "User Document Upload",
     "enables": "Marketers to upload their own documents into the tool for AI to use",
     "outOfScope": "Import of documents above a certain size, imports of large numbers of documents, upload from non-local files",
     "notes": "Build a Librarian Agent that supports document ingestion and retrieval",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Access to cloud storage location & the Document API domain",
     "size": "M",
     "risk": "S",
     "startDay": 30,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 31,
     "num": 22,
     "phaseId": "mvp-diagnosis",
     "workstream": "Process",
     "epic": "Process",
     "feature": "RACI, Role, and Approval Workflow Discovery",
     "enables": "Developers to have a clear definition of ownership and approval processes for all activities in scope, including edge cases like undo approval",
     "outOfScope": "Non-MVP activity analysis",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Activity and data ownership decisions, work-platform-OS integration approach",
     "size": "L",
     "risk": "L",
     "startDay": 30,
     "durDays": 20,
     "leadDays": 0,
     "barColor": "9BBB59",
     "bucketMark": null
    },
    {
     "row": 32,
     "num": 35,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Role Based Access Control (OpenFGA)",
     "enables": "Marketers to have access to only the necessary information for their role, and later get notified to complete actions based on their role.",
     "outOfScope": "",
     "notes": "",
     "deps": [
      22
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Roster samples, requirements alignment",
     "size": "L",
     "risk": "M",
     "startDay": 30,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 33,
     "num": 65,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Roster and Assignments",
     "enables": "Leads to grant additional/specific permissions to marketers at the activity step level, and assign activities to individuals for task tracking purposes. Leads to visualize task progress across programs and projects.",
     "outOfScope": "",
     "notes": "",
     "deps": [
      22
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "M",
     "risk": "M",
     "startDay": 40,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 34,
     "num": 29,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "In-OS Agent Feedback",
     "enables": "Marketers to provide feedback on agent quality within the tool via thumbs up/down, quality ratings, capture of primary errors, etc.",
     "outOfScope": "",
     "notes": "Design time; To Confirm - this is just data capture, yes/no? No direction integration of feedback into the application?",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "L",
     "risk": "M",
     "startDay": 40,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 35,
     "num": 31,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Guardrails",
     "enables": "Agents to follow Data Office and generally-recommended AI security stance. Marketers to see results with less marketer-created bias.",
     "outOfScope": "Bias evaluation",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Convo with the AI compliance lead on expected guardrails, the enterprise AI compliance requirements",
     "size": "L",
     "risk": "M",
     "startDay": 40,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 36,
     "num": 32,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Policies (Research and Implementation)",
     "enables": "Agents to follow clearly-defined rules based on the enterprise compliance requirements as well as specific marketer input. This codifies how agents behave under various scenarios, and inludes business-oriented policies as well (such as a \"pricing policy\").",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "the enterprise AI compliance requirements, marketer conversations",
     "size": "L",
     "risk": "M",
     "startDay": 40,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 37,
     "num": 33,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Agent Escalations (Warnings and Blockers)",
     "enables": "Agents to notify users during their work when they have questions, which allows marketers to more powerfully impact agent behavior mid-work. An example is if there are two conflicting answers in our data or two different ways to cut the data that may yield different results. Or contradictions or lack of certainty.",
     "outOfScope": "",
     "notes": "",
     "deps": [
      31,
      32
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "M",
     "risk": "M",
     "startDay": 50,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 38,
     "num": 34,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Analytics and Measures (MVP)",
     "enables": "Leaders to see value, success (quality/acceptance), risk/trust, and adoption KPIs within the tool. The research lead has a list of metrics (quantitative and qualitative) that we should use.",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Stakeholder alignment on specific analytics to track (based on production goals and go/no-go decisioning stance)",
     "size": "L",
     "risk": "L",
     "startDay": 50,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 39,
     "num": 46,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Artifact Visualizations (Charts and Maps) (TBD)",
     "enables": "Marketers to see AI-generated charts and graphs within artifacts based on real data. Enables some outputs to be accurate to the real sample documents.",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Sample documents that need visualizations",
     "size": "M",
     "risk": "M",
     "startDay": 50,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 40,
     "num": 66,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "Agents",
     "feature": "Context Gathering Agent Team (MVP) Refinement",
     "enables": "Any additional agents to enhance the capabilities of the context gathering agent team",
     "outOfScope": "",
     "notes": "At least: Brand and Competitive Agent, Ask Audience & Audience Optimizer,",
     "deps": [
      20,
      56
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "L",
     "risk": "M",
     "startDay": 40,
     "durDays": 20,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 41,
     "num": 69,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "Production Compliance and Setup",
     "enables": "Marketers to use this tool in production",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Data Office production compliance checklist, Permit to Operate",
     "size": "XL",
     "risk": "XL",
     "startDay": 40,
     "durDays": 40,
     "leadDays": 20,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 42,
     "num": 70,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "QA Testing",
     "enables": "Reduction of bugs and issues in UAT",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "Permit to Operate",
     "size": "L",
     "risk": "M",
     "startDay": 60,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 43,
     "num": 71,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "User Acceptance Testing",
     "enables": "Marketers to provide direct feedback on the product",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "Permit to Operate",
     "size": "XL",
     "risk": "M",
     "startDay": 60,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 44,
     "num": 72,
     "phaseId": "mvp-diagnosis",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "Launch and Hypercare",
     "enables": "Marketers to use the software, and for immediate bugs to be resolved",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "None",
     "size": "L",
     "risk": "None",
     "startDay": 80,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 46,
     "num": 73,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Agents",
     "feature": "Spike & Integration: Ask Strategy Agent (TBD)",
     "enables": "Strategy agents to utilize a pre-trained strategic agent for historical strategy information",
     "outOfScope": "Changing the Ask Strategy agent",
     "notes": "Unsure about this agent's capabilities, data access, and scope",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Competitive Intelligence data access alignment, Agent available and ready in Agent Platform",
     "size": "M",
     "risk": "M",
     "startDay": 80,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 47,
     "num": 25,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Approval Workflow",
     "enables": "Marketers to complete artifact approvals within the OS, and be able to complete a multi-step approval process. This includes locking and unlocking documents based on status (e.g. docs approved in the work management platform have to be manually unlocked).",
     "outOfScope": "",
     "notes": "Potential the work management platform integration",
     "deps": [
      22,
      24
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "None",
     "size": "M",
     "risk": "M",
     "startDay": 80,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 48,
     "num": 27,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Integrations",
     "feature": "Brief Builder UI Migration (MVP)",
     "enables": "Remaining brief UI features and key UI requirements to move into the OS",
     "outOfScope": "Shutdown of the Brief Builder UI",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Brief Builder ready to migrate to OS (timeline alignment), Brief Builder agents fully in Agent Platform (no stub)",
     "size": "L",
     "risk": "L",
     "startDay": 80,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 49,
     "num": 24,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Integrations",
     "feature": "Work Management Platform Integration",
     "enables": "the work management platform to remain source of truth for final artifacts and time-based activity reporting, while OS owns and syncs the end-to-end executional workflows",
     "outOfScope": "OS replacing the work management platform's capabilities, but there is overlap that needs discussion",
     "notes": "",
     "deps": [
      22
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "work-platform-OS use case alignment and mapping exercise, full API access",
     "size": "L",
     "risk": "L",
     "startDay": 110,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 50,
     "num": 39,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Agents",
     "feature": "Strategy Agent & GTM Team (MVP)",
     "enables": "Marketers to complete strategy phase in OS for the pilot initiative type. Includes testing against all use cases.",
     "outOfScope": "",
     "notes": "Need to discuss how we are including  some sort of channel history layer that uses past channel assets/campaigns in order to make the channel recommendation in the strategy phase\n\nIncludes at least: Ask Strategy agent and Channel Expert Team Lead\n\nAt least: Messaging Scoring Agent, GTM Planner Team Lead",
     "deps": [
      20,
      56,
      23,
      34
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Detailed discovery (\"Gold\" output documents etc.)",
     "size": "XL",
     "risk": "M",
     "startDay": 120,
     "durDays": 20,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 51,
     "num": 61,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Strategy End-to-End Workflow Implementation (MVP)",
     "enables": "Marketers to complete the end-to-end strategy-phase workflows",
     "outOfScope": "",
     "notes": "",
     "deps": [
      39,
      40
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Rounds of marketer review and feedback",
     "size": "L",
     "risk": "L",
     "startDay": 130,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 52,
     "num": 74,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "QA Testing",
     "enables": "Reduction of bugs and issues in UAT",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "Permit to Operate",
     "size": "L",
     "risk": "M",
     "startDay": 160,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 53,
     "num": 75,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "User Acceptance Testing",
     "enables": "Marketers to provide direct feedback on the product",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "Permit to Operate",
     "size": "XL",
     "risk": "M",
     "startDay": 160,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 54,
     "num": 76,
     "phaseId": "mvp-strategy",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "Launch and Hypercare",
     "enables": "Marketers to use the software, and for immediate bugs to be resolved",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "None",
     "size": "L",
     "risk": "None",
     "startDay": 180,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 56,
     "num": 40,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "Agents",
     "feature": "Communication Development Team (MVP)",
     "enables": "Marketers to complete communication development activity in OS.",
     "outOfScope": "",
     "notes": "Includes at least: Lead Copywriter Agent, Comms Team Lead (Editor)",
     "deps": [
      20,
      56
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Detailed discovery (\"Gold\" output documents etc.)",
     "size": "L",
     "risk": "M",
     "startDay": 170,
     "durDays": 20,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 57,
     "num": 64,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "Agents",
     "feature": "Message Scoring Agent",
     "enables": "Marketers can see message scoring in execution phase and how it performs per segment",
     "outOfScope": "",
     "notes": "Accessed through audience optimizer; a member of the Context Gathering Agent Team and GTM Agent Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Discovery around agent features, agent in Agent Platform",
     "size": "L",
     "risk": "M",
     "startDay": 170,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 58,
     "num": 62,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Execution End-to-End Workflow Implementation (MVP)",
     "enables": "Marketers to complete the end-to-end execution-phase workflows",
     "outOfScope": "",
     "notes": "",
     "deps": [
      41
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Rounds of marketer review and feedback",
     "size": "L",
     "risk": "L",
     "startDay": 160,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 59,
     "num": 43,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Multi-User Collaboration",
     "enables": "Multiple marketers to simultaneously collaborate on an artifact document",
     "outOfScope": "",
     "notes": "We already have some live sync via WebSockets, we want to make this more robust (for example, by using queues and ensuring conflict detection works)",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "the enterprise approval on real-time browser/API protocol",
     "size": "M",
     "risk": "M",
     "startDay": 170,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 60,
     "num": 44,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Global Search Bar",
     "enables": "Marketers to search for initiatives and documents across the user experience",
     "outOfScope": "Full text document search (only searches titles). AI-assisted search.",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Data Office Alignment on search index approach, architectural approval",
     "size": "L",
     "risk": "L",
     "startDay": 170,
     "durDays": 20,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 61,
     "num": 45,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Notifications",
     "enables": "Marketers to receive email and in-app notifications when an activity needs their action",
     "outOfScope": "Teams notifications",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Requirements validation",
     "size": "S",
     "risk": "M",
     "startDay": 180,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 62,
     "num": 47,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Artifact Download and Printing",
     "enables": "Marketers to download artifacts and print them out to PDF or printers",
     "outOfScope": "Download to places other than their local file system",
     "notes": "",
     "deps": [
      46
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "File type requirements, export requirements & samples for special cases like briefs",
     "size": "M",
     "risk": "M",
     "startDay": 180,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 63,
     "num": 77,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "QA Testing",
     "enables": "Reduction of bugs and issues in UAT",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "Permit to Operate",
     "size": "L",
     "risk": "M",
     "startDay": 190,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 64,
     "num": 78,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "User Acceptance Testing",
     "enables": "Marketers to provide direct feedback on the product",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "Permit to Operate",
     "size": "XL",
     "risk": "M",
     "startDay": 190,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 65,
     "num": 79,
     "phaseId": "mvp-execution",
     "workstream": "Product",
     "epic": "Testing",
     "feature": "Launch and Hypercare",
     "enables": "Marketers to use the software, and for immediate bugs to be resolved",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": true,
     "depsText": [],
     "extDeps": "None",
     "size": "L",
     "risk": "None",
     "startDay": 210,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 67,
     "num": 57,
     "phaseId": "next",
     "workstream": "Product / Process",
     "epic": "OS",
     "feature": "MVP Phase Initiative Type Determination",
     "enables": "Non-pilot initiatives to be tested against in the system",
     "outOfScope": "",
     "notes": "Build evaluations that test success of artifacts and agents across workflows",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Sample",
     "size": "M",
     "risk": "M",
     "startDay": 30,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 68,
     "num": 80,
     "phaseId": "next",
     "workstream": "Product",
     "epic": "Integrations",
     "feature": "Terms & Taxonomy Integration (MVP)",
     "enables": "Keep the agents in sync with terms & taxonomy changes",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Broader Terms & Taxonomy must be defined by the enterprise and made available as a maintained data source",
     "size": "S",
     "risk": "M",
     "startDay": 50,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 69,
     "num": 59,
     "phaseId": "next",
     "workstream": "Process",
     "epic": "OS",
     "feature": "Intake Discovery",
     "enables": "MVP 2 to create a working intake for the 2-3 use cases defined",
     "outOfScope": "",
     "notes": "User Experience, governance, data, etc.",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Detailed discovery",
     "size": "L",
     "risk": "M",
     "startDay": 40,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "9BBB59",
     "bucketMark": null
    },
    {
     "row": 70,
     "num": 28,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Initiative Intake",
     "enables": "Marketers to create, organize, and prioritize new initiatives within the tool",
     "outOfScope": "Creation of an annual plan, import of annual planned initiatives",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Marketer interviews, sample intake data",
     "size": "L",
     "risk": null,
     "startDay": 40,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "71A1DC",
     "bucketMark": null
    },
    {
     "row": 71,
     "num": 81,
     "phaseId": "next",
     "workstream": "Product",
     "epic": "Data",
     "feature": "Offer Library Data Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "Probably a the intranet integration…",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Detailed discovery",
     "size": "M",
     "risk": "L",
     "startDay": 60,
     "durDays": 20,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 72,
     "num": 56,
     "phaseId": "next",
     "workstream": "Product / Process",
     "epic": "Agents",
     "feature": "Strategy and Execution Detailed Process Discovery for MVP",
     "enables": "OS to define clear and accurate agents aligned with marketer expectations, for the strategy and execution phases. Goal is to define task-level process and align data sources to agents. Turn the capabilities defined by process team into agent prompts.",
     "outOfScope": "Building any agents",
     "notes": "It's important to define the shape of governance components in our framework beforehand so that we can clearly prompt users to answer detailed process questions for us",
     "deps": [
      31,
      32,
      34,
      57
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Access to marketers, data access as above, capabilities and process defined",
     "size": "L",
     "risk": "M",
     "startDay": 90,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "9BBB59",
     "bucketMark": null
    },
    {
     "row": 73,
     "num": 67,
     "phaseId": "next",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Artifact Sharing",
     "enables": "Marketers to share an artifact with others, both in and outside the the enterprise organization, to enable artifact collaboration between agencies and the enterprise",
     "outOfScope": "",
     "notes": "",
     "deps": [
      22,
      47
     ],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Requirements, the enterprise permission to have a public-facing application (RISK!)",
     "size": "L",
     "risk": "XL",
     "startDay": 120,
     "durDays": 30,
     "leadDays": 10,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 74,
     "num": 49,
     "phaseId": "next",
     "workstream": "Product",
     "epic": "OS",
     "feature": "Onboarding User Experience",
     "enables": "Marketers to have a clear and navigable experience from their first time logging in",
     "outOfScope": "FAQ, help pages (these would be in the intranet outside the tool, for easy editability)",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Marketer feedback, OCM dependency",
     "size": "M",
     "risk": "M",
     "startDay": 130,
     "durDays": 10,
     "leadDays": 0,
     "barColor": "4F81BD",
     "bucketMark": null
    },
    {
     "row": 75,
     "num": 82,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Annual Plan Initiative Import",
     "enables": "Marketers to see supported initiatives from the annual plan directly in the tool.",
     "outOfScope": "Creation of an annual plan",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 76,
     "num": 83,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Data Integration Enhancements (Scope TBD)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": 130,
     "durDays": 110,
     "leadDays": 0,
     "barColor": "71A1DC",
     "bucketMark": null
    },
    {
     "row": 79,
     "num": 84,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Plan the Plan (Annual Planning) Spine",
     "enables": "Marketers to complete all annual planning activities in the OS. work-platform-aligned.",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 80,
     "num": 85,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Next-Phase Focused Data Catalogue Discovery and Development",
     "enables": "With data access in hand, additional discovery and integration approach recommendation for data sources. Gain additional fidelity on maturity where access permits. Specifically focusing on pre-Measurement data sources identified as \"Next\".",
     "outOfScope": "",
     "notes": "Include any uncertain external agent discovery (Consumer, the martech vendor, etc.)",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Full access to data sources as discovered",
     "size": "XL",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 81,
     "num": 86,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Measurement Phase Data Catalogue Discovery and Development",
     "enables": "With data access in hand, additional discovery and integration approach recommendation for data sources. Gain additional fidelity on maturity where access permits. Specifically focusing on Execution and Measurement.",
     "outOfScope": "",
     "notes": "Include any uncertain external agent discovery (Consumer, the martech vendor, etc.)",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Full access to data sources as discovered",
     "size": "XL",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 82,
     "num": 87,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Measurement Detailed Process Discovery",
     "enables": "OS to define clear and accurate agents aligned with marketer expectations, for the measurement phase. Goal is to define task-level process and align data sources to agents.",
     "outOfScope": "Building any agents",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Access to marketers, data access as needed based on data discovery. Dependent on catalogue discovery above.",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 83,
     "num": 88,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Signals (Measurement) Dashboard",
     "enables": "Marketers to see and act on real-time prioritized agent outputs from the Measurement phase in a dashboard. Signals must be surfaced to the initiatives where they are relevant.",
     "outOfScope": "Setting up new custom signals",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Signal requirements",
     "size": "M",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 84,
     "num": 89,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Signal Discovery Agent",
     "enables": "Marketers to receive live signals related to measurement phase",
     "outOfScope": "Competitive intelligence and OSINT (public data) signals",
     "notes": "Part of Measurement Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Detailed discovery, signal requirements",
     "size": "L",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 85,
     "num": 90,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Process Customization / Step Skipping",
     "enables": "Marketers to skip steps and provide AI feedback on how their particular process differs from the current process. Process stewards to see why and when steps were skipped.",
     "outOfScope": "Allowing process stewards to change the process based on patterns of steps skipped - this is another feature",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 86,
     "num": 91,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Campaign Performance Data Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 87,
     "num": 92,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Competitive Intelligence Agents",
     "enables": "",
     "outOfScope": "",
     "notes": "Members of the Context Gathering Agent Teams",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Access to the competitive intelligence data sources",
     "size": "XL",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 88,
     "num": 93,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Competitive Intelligence Integrations",
     "enables": "",
     "outOfScope": "",
     "notes": "ex: Competitive Intelligence Hub",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 89,
     "num": 94,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Analytics (Post-MVP)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 90,
     "num": 95,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agent Platform",
     "feature": "A2A Protocol Standardization (TBD)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 91,
     "num": 96,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agent Platform",
     "feature": "Internet Search and Fetch Tool and Policies (TBD)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 92,
     "num": 97,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agent Platform",
     "feature": "Agent Registry",
     "enables": "OS to utilize agents outside the workspace of the platform team",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 93,
     "num": 98,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agent Platform",
     "feature": "Skill / Capability Registry (TBD)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 94,
     "num": 99,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agent Platform",
     "feature": "Knowledge Registry (TBD)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 95,
     "num": 100,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agent Platform",
     "feature": "Memory, Feedback, Learning (TBD)",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 96,
     "num": 101,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Creative Review Agent (Platform) & Creative Lead Agent (OS Built)",
     "enables": "",
     "outOfScope": "",
     "notes": "Member of the GTM Agent Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 97,
     "num": 102,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Channel-Specific Execution/Activation Agents",
     "enables": "",
     "outOfScope": "",
     "notes": "Includes at least: TV / Advanced TV Agent\nAudio Agent\nOut of Home Agent\nSponsorships / Events Agent\nInfluencer Agent\nAffiliate Agent\nDisplay Agent\nOnline Video Agent\nPaid Search Agent\nPaid Social Agent\nE-Commerce Agent\nWebsite Agent\nDigital Apps Agent\nEmail / Direct Mail / SMS Agent\nCall Center / Outbound Telemarketing Agent\nRetail Agent\nInternal Communications Agent\nOrganic Social Agent\nPrint Agent\nOrganic Search (SEO) Agent\nPublic Relations Agent\nCreative Lead, enhancements to the Channel Expert Team Lead,",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 98,
     "num": 103,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Long-Term AI Warehousing",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 99,
     "num": 104,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Playbook / Historical Campaign Data Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 100,
     "num": 105,
     "phaseId": "next",
     "workstream": "",
     "epic": "Data",
     "feature": "Competitive Intelligence Data Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 101,
     "num": 106,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Digital Asset Management Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 102,
     "num": 107,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Competitive Data Vendor Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 103,
     "num": 108,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Customer Data Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 104,
     "num": 109,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Journey Orchestration Agent Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "Member of the follow teams: Context Gathering Agent, Strategy Agent Team, Communication Development Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 105,
     "num": 110,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Marketing Data Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 106,
     "num": 111,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Marketing Planning Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 107,
     "num": 112,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Strategy Agent Team (Next)",
     "enables": "",
     "outOfScope": "",
     "notes": "Includes at least: Budget and Insights Agent, Strategic Simulation and Testing Agent, Historical Strategic Expert Agent",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [
      "Marketing Planning Platform Integration"
     ],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 108,
     "num": 113,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Consumer Competitive Intelligence Agents / Integrations",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [
      "Deep review of agent capabilities (with code)",
      "Alignment on Competitive Intelligence agent & data source use"
     ],
     "extDeps": "",
     "size": "L",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 109,
     "num": 114,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "System-Wide Intake and Governance",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 110,
     "num": 115,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Learning and Memory Governance",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 111,
     "num": 116,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Artifact Version History and Diff",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 112,
     "num": 117,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Recurring / Scheduled Activities",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 113,
     "num": 118,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Global Ask AI",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 114,
     "num": 119,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Process Admin UI",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 115,
     "num": 120,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Executive Dashboard",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 116,
     "num": 121,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Forecasting Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 117,
     "num": 122,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Early KPI Forecasting",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 118,
     "num": 123,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Agent Memory",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 119,
     "num": 124,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Cross-Initiative Dependencies",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 120,
     "num": 125,
     "phaseId": "next",
     "workstream": "",
     "epic": "OS",
     "feature": "Interruption",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 121,
     "num": 126,
     "phaseId": "next",
     "workstream": "",
     "epic": "Workflows",
     "feature": "Post-Pilot Workflow End-to-End",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 122,
     "num": 127,
     "phaseId": "next",
     "workstream": "",
     "epic": "Agents",
     "feature": "Measurement Phase Agents",
     "enables": "Marketers to utilize agents to support measurement phase signal discovery and creation / update of initiatives based on these signals. This may include Social Listening agents if pulling OSINT data is in scope.",
     "outOfScope": "Scope uncertain, needs process research",
     "notes": "Includes at least the Measurement Team Lead and Performance Intelligence Analyst, Signals Discovery Analyst",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [
      "Process team research of measurement process",
      "Measurement data discovery",
      "Access to measurement-related data sources"
     ],
     "extDeps": "",
     "size": "L",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 123,
     "num": 128,
     "phaseId": "next",
     "workstream": "",
     "epic": "Workflows",
     "feature": "Artifact Process Post-Approval",
     "enables": ".",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 124,
     "num": 129,
     "phaseId": "next",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Headless CMS Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 126,
     "num": 130,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Future Scope Data Catalogue Discovery and Development",
     "enables": "With data access in hand, additional discovery and integration approach recommendation for data sources. Gain additional fidelity on maturity where access permits. Specifically focusing on data sets that are external to the enterprise or otherwise in future scope.",
     "outOfScope": "",
     "notes": "Include external OSINT-based data (such as Google Trends, etc.) that has not yet been identified or integrated in our platform.",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "Full access to data sources as discovered",
     "size": "XL",
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 127,
     "num": 131,
     "phaseId": "future",
     "workstream": "",
     "epic": "Agents",
     "feature": "Legal Review Agent",
     "enables": "",
     "outOfScope": "",
     "notes": "Part of Comms Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 128,
     "num": 132,
     "phaseId": "future",
     "workstream": "",
     "epic": "Agents",
     "feature": "Visual Asset Creation Agents",
     "enables": "",
     "outOfScope": "",
     "notes": "Member of the GTM Agent Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 129,
     "num": 133,
     "phaseId": "future",
     "workstream": "",
     "epic": "Agents",
     "feature": "Public Data Deep Research (OSINT) Agent",
     "enables": "",
     "outOfScope": "Data ingestion (that is, copying) from external data sources. This must be handled at the data layer by the enterprise.",
     "notes": "Member of the Context Gathering Agent Team",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "next-bucket"
    },
    {
     "row": 130,
     "num": 134,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Data Warehouse Integration and Mapping",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 131,
     "num": 135,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Intake System Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 132,
     "num": 136,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Ad Server Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 133,
     "num": 137,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Creative Studio Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 134,
     "num": 138,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Pricing Engine Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 135,
     "num": 139,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Email Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 136,
     "num": 140,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Creative Automation Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 137,
     "num": 141,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Messaging Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 138,
     "num": 142,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Web Content Management Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 139,
     "num": 143,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Journey Analytics Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 140,
     "num": 144,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Personalization Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 141,
     "num": 145,
     "phaseId": "future",
     "workstream": "",
     "epic": "Integrations",
     "feature": "Churn Platform Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 142,
     "num": 146,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Organic Social Data Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 143,
     "num": 147,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Consumer Survey Data Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    },
    {
     "row": 144,
     "num": 148,
     "phaseId": "future",
     "workstream": "",
     "epic": "Data",
     "feature": "Google Trends Integration",
     "enables": "",
     "outOfScope": "",
     "notes": "",
     "deps": [],
     "depsAllAbove": false,
     "depsText": [],
     "extDeps": "",
     "size": null,
     "risk": null,
     "startDay": null,
     "durDays": null,
     "leadDays": 0,
     "barColor": null,
     "bucketMark": "future-bucket"
    }
   ]
  };
  root.RM_SEED = SEED;
  if (typeof module !== "undefined" && module.exports) module.exports = SEED;
})(typeof window !== "undefined" ? window : globalThis);
